/* Automatically generated header (sfdc 1.11d)! Do not edit! */

#ifndef CLIB_MUIMASTER_PROTOS_H
#define CLIB_MUIMASTER_PROTOS_H

/*
**   $VER: muimaster_protos.h  
**
**   C prototypes. For use with 32 bit integers only.
**
**   Copyright (c) 2001 Amiga, Inc.
**       All Rights Reserved
*/

#include <exec/types.h>
#include <intuition/classes.h>
#include <utility/tagitem.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* This SFD file was automatically generated by fd2sfd from */
/* muimaster_lib.fd and */
/* ../C/Include/clib/muimaster_protos.h. */
Object * MUI_NewObjectA(char * class, struct TagItem * tags);
Object * MUI_NewObject(char * class, Tag tags, ...);
VOID MUI_DisposeObject(Object * obj);
LONG MUI_RequestA(APTR app, APTR win, LONGBITS flags, char * title, char * gadgets, char * format, APTR params);
LONG MUI_Request(APTR app, APTR win, LONGBITS flags, char * title, char * gadgets, char * format, ...);
APTR MUI_AllocAslRequest(unsigned long type, struct TagItem * tags);
APTR MUI_AllocAslRequestTags(unsigned long type, Tag tags, ...);
BOOL MUI_AslRequest(APTR req, struct TagItem * tags);
BOOL MUI_AslRequestTags(APTR req, Tag tags, ...);
VOID MUI_FreeAslRequest(APTR req);
LONG MUI_Error(void);
LONG MUI_SetError(LONG errnum);
struct IClass * MUI_GetClass(char * name);
VOID MUI_FreeClass(struct IClass * cl);
VOID MUI_RequestIDCMP(Object * obj, ULONG flags);
VOID MUI_RejectIDCMP(Object * obj, ULONG flags);
VOID MUI_Redraw(Object * obj, ULONG flags);
struct MUI_CustomClass * MUI_CreateCustomClass(struct Library * base, char * supername, struct MUI_CustomClass * supermcc, int datasize, APTR dispatcher);
BOOL MUI_DeleteCustomClass(struct MUI_CustomClass * mcc);
Object * MUI_MakeObjectA(LONG type, ULONG * params);
Object * MUI_MakeObject(LONG type, ...);
BOOL MUI_Layout(Object * obj, LONG l, LONG t, LONG w, LONG h, ULONG flags);
LONG MUI_ObtainPen(struct MUI_RenderInfo * mri, struct MUI_PenSpec * spec, ULONG flags);
VOID MUI_ReleasePen(struct MUI_RenderInfo * mri, LONG pen);
APTR MUI_AddClipping(struct MUI_RenderInfo * mri, WORD l, WORD t, WORD w, WORD h);
VOID MUI_RemoveClipping(struct MUI_RenderInfo * mri, APTR h);
APTR MUI_AddClipRegion(struct MUI_RenderInfo * mri, struct Region * region);
VOID MUI_RemoveClipRegion(struct MUI_RenderInfo * mri, APTR region);
BOOL MUI_BeginRefresh(struct MUI_RenderInfo * mri, ULONG flags);
VOID MUI_EndRefresh(struct MUI_RenderInfo * mri, ULONG flags);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_MUIMASTER_PROTOS_H */
